// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_o
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4sJ70j5RYVXr44UxBbuGWkdH48SA2zi0',
    appId: '1:192803325042:web:6cb46779ef5b5a210beeeb',
    messagingSenderId: '192803325042',
    projectId: 'quizmaster-870c0',
    authDomain: 'quizmaster-870c0.firebaseapp.com',
    storageBucket: 'quizmaster-870c0.firebasestorage.app',
    measurementId: 'G-TRDVQT624F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu2rm8PLWaieuPn3gdYHqgcWSBamKUdWo',
    appId: '1:192803325042:android:c6f9da9829307ec20beeeb',
    messagingSenderId: '192803325042',
    projectId: 'quizmaster-870c0',
    storageBucket: 'quizmaster-870c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKrrOADFiDhHt0ZKXBLd_mViyqXa8EE18',
    appId: '1:192803325042:ios:88abf2304dc314980beeeb',
    messagingSenderId: '192803325042',
    projectId: 'quizmaster-870c0',
    storageBucket: 'quizmaster-870c0.firebasestorage.app',
    iosClientId: '192803325042-3k1iipv723qafn6amjsmvpu488ug31ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKrrOADFiDhHt0ZKXBLd_mViyqXa8EE18',
    appId: '1:192803325042:ios:88abf2304dc314980beeeb',
    messagingSenderId: '192803325042',
    projectId: 'quizmaster-870c0',
    storageBucket: 'quizmaster-870c0.firebasestorage.app',
    iosClientId: '192803325042-3k1iipv723qafn6amjsmvpu488ug31ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4sJ70j5RYVXr44UxBbuGWkdH48SA2zi0',
    appId: '1:192803325042:web:8a1237ed9700ea650beeeb',
    messagingSenderId: '192803325042',
    projectId: 'quizmaster-870c0',
    authDomain: 'quizmaster-870c0.firebaseapp.com',
    storageBucket: 'quizmaster-870c0.firebasestorage.app',
    measurementId: 'G-48LVNZFXNN',
  );

}